INSERT INTO integration_definition (
    client_name,
    base_url,
    enabled,
    schedule_cron,
    csv_file_name,
    output_directory,
    max_retries,
    auth_config,
    response_config,
    pagination_config,
    storage_config,
    step_config
) VALUES (
    'Seed Demo - No Auth JSON Local',
    'https://dummy-no-auth.example.com/api',
    b'0',
    '0 0 2 * * *',
    'seed_no_auth_orders.csv',
    'output/demo/no-auth',
    2,
    CAST('{"type":"NONE"}' AS JSON),
    CAST('{"recordPath":"$.data.orders","recordPathType":"JSON_PATH"}' AS JSON),
    CAST('{"enabled":true,"mode":"PAGE_NUMBER","startPage":1,"pageParam":"page","totalPagesPath":"$.meta.totalPages","totalPagesPathType":"JSON_PATH"}' AS JSON),
    CAST('{"type":"LOCAL","localDirectory":"output/demo/no-auth"}' AS JSON),
    CAST('[{"orderIndex":1,"name":"fetch-orders","method":"GET","url":"/orders","queryParams":{"businessDate":"${today}","page":"${page}"},"requestFormat":"JSON","responseFormat":"JSON","paginate":true,"dataStep":true,"responseAlias":"ordersResponse"}]' AS JSON)
);

INSERT INTO integration_definition (
    client_name,
    base_url,
    enabled,
    schedule_cron,
    csv_file_name,
    output_directory,
    max_retries,
    auth_config,
    response_config,
    storage_config,
    step_config
) VALUES (
    'Seed Demo - Basic JSON Local',
    'https://dummy-basic.example.com/api',
    b'0',
    '0 15 2 * * *',
    'seed_basic_students.csv',
    'output/demo/basic',
    1,
    CAST('{"type":"BASIC","username":"demo-user","password":"demo-pass"}' AS JSON),
    CAST('{"recordPath":"$.data.students","recordPathType":"JSON_PATH"}' AS JSON),
    CAST('{"type":"LOCAL","localDirectory":"output/demo/basic"}' AS JSON),
    CAST('[{"orderIndex":1,"name":"fetch-students","method":"GET","url":"/students","queryParams":{"campus":"north"},"requestFormat":"JSON","responseFormat":"JSON","dataStep":true}]' AS JSON)
);

INSERT INTO integration_definition (
    client_name,
    base_url,
    enabled,
    schedule_cron,
    csv_file_name,
    output_directory,
    max_retries,
    auth_config,
    response_config,
    storage_config,
    step_config
) VALUES (
    'Seed Demo - API Key Header XML FTP',
    'https://dummy-header-xml.example.com/service',
    b'0',
    '0 30 2 * * *',
    'seed_header_xml_employees.csv',
    'output/demo/header-xml',
    1,
    CAST('{"type":"API_KEY_HEADER","headerName":"X-API-KEY","headerValue":"demo-header-key"}' AS JSON),
    CAST('{"recordPath":"//Employees/Employee","recordPathType":"XPATH"}' AS JSON),
    CAST('{"type":"FTP","host":"ftp.example.com","port":21,"username":"demo-ftp","password":"demo-ftp-pass","remoteDirectory":"/exports/employees","passiveMode":true}' AS JSON),
    CAST('[{"orderIndex":1,"name":"fetch-employees-xml","method":"GET","url":"/employees","requestFormat":"XML","responseFormat":"XML","dataStep":true}]' AS JSON)
);

INSERT INTO integration_definition (
    client_name,
    base_url,
    enabled,
    schedule_cron,
    csv_file_name,
    output_directory,
    max_retries,
    auth_config,
    response_config,
    storage_config,
    step_config
) VALUES (
    'Seed Demo - API Key Query JSON Local',
    'https://dummy-query-key.example.com/api',
    b'0',
    '0 45 2 * * *',
    'seed_query_key_items.csv',
    'output/demo/query-key',
    1,
    CAST('{"type":"API_KEY_QUERY","queryParamName":"apiKey","queryParamValue":"demo-query-key"}' AS JSON),
    CAST('{"recordPath":"$.items","recordPathType":"JSON_PATH"}' AS JSON),
    CAST('{"type":"LOCAL","localDirectory":"output/demo/query-key"}' AS JSON),
    CAST('[{"orderIndex":1,"name":"fetch-items","method":"GET","url":"/inventory/items","queryParams":{"warehouse":"WH01"},"requestFormat":"JSON","responseFormat":"JSON","dataStep":true}]' AS JSON)
);

INSERT INTO integration_definition (
    client_name,
    base_url,
    enabled,
    schedule_cron,
    csv_file_name,
    output_directory,
    max_retries,
    auth_config,
    response_config,
    storage_config,
    step_config
) VALUES (
    'Seed Demo - Bearer Static SOAP S3',
    'https://dummy-soap-bearer.example.com/services',
    b'0',
    '0 0 3 * * *',
    'seed_bearer_soap_invoices.csv',
    'output/demo/bearer-soap',
    2,
    CAST('{"type":"BEARER_STATIC","headerValue":"demo-static-token","tokenPrefix":"Bearer "}' AS JSON),
    CAST('{"recordPath":"//*[local-name()=''Envelope'']/*[local-name()=''Body'']/*[local-name()=''Invoices'']/*[local-name()=''Invoice'']","recordPathType":"XPATH"}' AS JSON),
    CAST('{"type":"S3","bucket":"demo-client-exports","region":"ap-south-1","keyPrefix":"soap/invoices"}' AS JSON),
    CAST('[{"orderIndex":1,"name":"fetch-invoices-soap","method":"POST","url":"/invoiceService","requestFormat":"SOAP","responseFormat":"SOAP","dataStep":true}]' AS JSON)
);

INSERT INTO integration_definition (
    client_name,
    base_url,
    enabled,
    schedule_cron,
    csv_file_name,
    output_directory,
    max_retries,
    auth_config,
    response_config,
    storage_config,
    step_config
) VALUES (
    'Seed Demo - Token API JSON Local',
    'https://dummy-token-api.example.com/api',
    b'0',
    '0 15 3 * * *',
    'seed_token_api_transactions.csv',
    'output/demo/token-api',
    3,
    CAST('{"type":"TOKEN_API","method":"POST","tokenUrl":"https://dummy-token-api.example.com/oauth/token","requestFormat":"JSON","responseFormat":"JSON","tokenPath":"$.access_token","tokenPathType":"JSON_PATH","tokenHeaderName":"Authorization","tokenPrefix":"Bearer "}' AS JSON),
    CAST('{"recordPath":"$.data.transactions","recordPathType":"JSON_PATH"}' AS JSON),
    CAST('{"type":"LOCAL","localDirectory":"output/demo/token-api"}' AS JSON),
    CAST('[{"orderIndex":1,"name":"start-session","method":"POST","url":"/sessions","requestFormat":"JSON","responseFormat":"JSON","dataStep":false,"responseVariables":{"$.sessionId":"sessionId"},"responseVariablePathType":"JSON_PATH"},{"orderIndex":2,"name":"fetch-transactions","method":"GET","url":"/transactions","queryParams":{"sessionId":"${sessionId}"},"requestFormat":"JSON","responseFormat":"JSON","dataStep":true}]' AS JSON)
);

INSERT INTO integration_definition (
    client_name,
    base_url,
    enabled,
    schedule_cron,
    csv_file_name,
    output_directory,
    max_retries,
    auth_config,
    response_config,
    pagination_config,
    storage_config,
    step_config
) VALUES (
    'Seed Demo - OAuth2 Client Credentials JSON Local',
    'https://dummy-oauth.example.com/api',
    b'0',
    '0 30 3 * * *',
    'seed_oauth_customers.csv',
    'output/demo/oauth2',
    2,
    CAST('{"type":"OAUTH2_CLIENT_CREDENTIALS","tokenUrl":"https://dummy-oauth.example.com/oauth/token","clientId":"demo-client-id","clientSecret":"demo-client-secret","scope":"read:customers","tokenHeaderName":"Authorization","tokenPrefix":"Bearer "}' AS JSON),
    CAST('{"recordPath":"$.customers","recordPathType":"JSON_PATH"}' AS JSON),
    CAST('{"enabled":true,"mode":"NEXT_URL","nextPagePath":"$.links.next","nextPagePathType":"JSON_PATH"}' AS JSON),
    CAST('{"type":"LOCAL","localDirectory":"output/demo/oauth2"}' AS JSON),
    CAST('[{"orderIndex":1,"name":"fetch-customers","method":"GET","url":"/customers","requestFormat":"JSON","responseFormat":"JSON","paginate":true,"dataStep":true}]' AS JSON)
);

INSERT INTO integration_field_mapping (
    integration_id,
    sort_order,
    mapping_type,
    source_path,
    path_type,
    target_header,
    expression,
    default_value,
    formatter,
    required_flag
) VALUES
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - No Auth JSON Local'),
    1,
    'SOURCE_PATH',
    '$.orderId',
    'JSON_PATH',
    'ORDER_ID',
    NULL,
    NULL,
    NULL,
    b'1'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - No Auth JSON Local'),
    2,
    'CONSTANT',
    NULL,
    NULL,
    'STORE_ID',
    '1',
    NULL,
    NULL,
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - No Auth JSON Local'),
    3,
    'EXPRESSION',
    NULL,
    NULL,
    'TOTAL_AMOUNT',
    'num(''$.net'') + num(''$.gross'')',
    '0',
    NULL,
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - Basic JSON Local'),
    1,
    'SOURCE_PATH',
    '$.studentId',
    'JSON_PATH',
    'STUDENT_ID',
    NULL,
    NULL,
    NULL,
    b'1'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - Basic JSON Local'),
    2,
    'CONSTANT',
    NULL,
    NULL,
    'CAMPUS_ID',
    '101',
    NULL,
    NULL,
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - Basic JSON Local'),
    3,
    'EXPRESSION',
    NULL,
    NULL,
    'FULL_NAME',
    'value(''$.firstName'') + '' '' + value(''$.lastName'')',
    NULL,
    NULL,
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - API Key Header XML FTP'),
    1,
    'SOURCE_PATH',
    './EmployeeId/text()',
    'XPATH',
    'EMPLOYEE_ID',
    NULL,
    NULL,
    NULL,
    b'1'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - API Key Header XML FTP'),
    2,
    'CONSTANT',
    NULL,
    NULL,
    'STORE_ID',
    '2',
    NULL,
    NULL,
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - API Key Header XML FTP'),
    3,
    'EXPRESSION',
    NULL,
    NULL,
    'GROSS_AMOUNT',
    'num(''./Net/text()'') + num(''./Gross/text()'')',
    '0',
    NULL,
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - API Key Query JSON Local'),
    1,
    'SOURCE_PATH',
    '$.item.code',
    'JSON_PATH',
    'ITEM_CODE',
    NULL,
    NULL,
    NULL,
    b'1'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - API Key Query JSON Local'),
    2,
    'CONSTANT',
    NULL,
    NULL,
    'SOURCE_SYSTEM',
    'CLIENT_A',
    NULL,
    'UPPERCASE',
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - API Key Query JSON Local'),
    3,
    'EXPRESSION',
    NULL,
    NULL,
    'EXTENDED_PRICE',
    'num(''$.qty'') * num(''$.price'')',
    '0',
    NULL,
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - Bearer Static SOAP S3'),
    1,
    'SOURCE_PATH',
    './InvoiceId/text()',
    'XPATH',
    'INVOICE_ID',
    NULL,
    NULL,
    NULL,
    b'1'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - Bearer Static SOAP S3'),
    2,
    'CONSTANT',
    NULL,
    NULL,
    'COUNTRY_CODE',
    'IN',
    NULL,
    'UPPERCASE',
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - Bearer Static SOAP S3'),
    3,
    'EXPRESSION',
    NULL,
    NULL,
    'GRAND_TOTAL',
    'num(''./Net/text()'') + num(''./Tax/text()'')',
    '0',
    NULL,
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - Token API JSON Local'),
    1,
    'SOURCE_PATH',
    '$.transactionId',
    'JSON_PATH',
    'TRANSACTION_ID',
    NULL,
    NULL,
    NULL,
    b'1'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - Token API JSON Local'),
    2,
    'CONSTANT',
    NULL,
    NULL,
    'STORE_ID',
    '5',
    NULL,
    NULL,
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - Token API JSON Local'),
    3,
    'EXPRESSION',
    NULL,
    NULL,
    'NET_PLUS_FEE',
    'num(''$.netAmount'') + num(''$.processingFee'')',
    '0',
    NULL,
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - OAuth2 Client Credentials JSON Local'),
    1,
    'SOURCE_PATH',
    '$.customer.id',
    'JSON_PATH',
    'CUSTOMER_ID',
    NULL,
    NULL,
    NULL,
    b'1'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - OAuth2 Client Credentials JSON Local'),
    2,
    'CONSTANT',
    NULL,
    NULL,
    'CHANNEL',
    'WEB',
    NULL,
    'UPPERCASE',
    b'0'
),
(
    (SELECT id FROM integration_definition WHERE client_name = 'Seed Demo - OAuth2 Client Credentials JSON Local'),
    3,
    'EXPRESSION',
    NULL,
    NULL,
    'CREDIT_LIMIT_USED',
    'num(''$.credit.used'') + num(''$.credit.pending'')',
    '0',
    NULL,
    b'0'
);
